# Generated by Django 6.0.4 on 2026-05-13 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_alter_profile_id'),
        ('Accounts', '0002_profile_avatar_alter_profile_user'),
    ]

    operations = [
    ]
